//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCluster) DeepCopyInto(out *GPUCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCluster.
func (in *GPUCluster) DeepCopy() *GPUCluster {
	if in == nil {
		return nil
	}
	out := new(GPUCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClusterList) DeepCopyInto(out *GPUClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClusterList.
func (in *GPUClusterList) DeepCopy() *GPUClusterList {
	if in == nil {
		return nil
	}
	out := new(GPUClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUClusterSpec) DeepCopyInto(out *GPUClusterSpec) {
	*out = *in
	out.Driver = in.Driver
	out.DevicePlugin = in.DevicePlugin
	out.GPUFeatureDiscovery = in.GPUFeatureDiscovery
	if in.ApplicationProfiles != nil {
		in, out := &in.ApplicationProfiles, &out.ApplicationProfiles
		*out = make([]ApplicationProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUClusterSpec) DeepCopy() *GPUClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GPUClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUClusterStatus) DeepCopyInto(out *GPUClusterStatus) {
	*out = *in
	in.Node.DeepCopyInto(&out.Node)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProfileStatuses != nil {
		in, out := &in.ProfileStatuses, &out.ProfileStatuses
		*out = make([]ProfileStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProfileStatus) DeepCopyInto(out *ProfileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProfileStatus) DeepCopy() *ProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUClusterStatus) DeepCopy() *GPUClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GPUClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	out.GPU = in.GPU
	out.Memory = in.Memory
}

// DeepCopy is an autogenerated deepcopy function.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *CPUNodeInfo) DeepCopyInto(out *CPUNodeInfo) {
	*out = *in
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function.
func (in *CPUNodeInfo) DeepCopy() *CPUNodeInfo {
	if in == nil {
		return nil
	}
	out := new(CPUNodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUNodeInfo) DeepCopyInto(out *GPUNodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUNodeInfo) DeepCopy() *GPUNodeInfo {
	if in == nil {
		return nil
	}
	out := new(GPUNodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *MemoryNodeInfo) DeepCopyInto(out *MemoryNodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *MemoryNodeInfo) DeepCopy() *MemoryNodeInfo {
	if in == nil {
		return nil
	}
	out := new(MemoryNodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DriverSpec) DeepCopyInto(out *DriverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DriverSpec) DeepCopy() *DriverSpec {
	if in == nil {
		return nil
	}
	out := new(DriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *DevicePluginSpec) DeepCopyInto(out *DevicePluginSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *DevicePluginSpec) DeepCopy() *DevicePluginSpec {
	if in == nil {
		return nil
	}
	out := new(DevicePluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *GPUFeatureDiscoverySpec) DeepCopyInto(out *GPUFeatureDiscoverySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *GPUFeatureDiscoverySpec) DeepCopy() *GPUFeatureDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(GPUFeatureDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ApplicationProfile) DeepCopyInto(out *ApplicationProfile) {
	*out = *in
	if in.HelmValues != nil {
		in, out := &in.HelmValues, &out.HelmValues
		*out = make(map[string]any, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ApplicationProfile) DeepCopy() *ApplicationProfile {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function.
func (in *ProfileResources) DeepCopyInto(out *ProfileResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function.
func (in *ProfileResources) DeepCopy() *ProfileResources {
	if in == nil {
		return nil
	}
	out := new(ProfileResources)
	in.DeepCopyInto(out)
	return out
}
