apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ai-stack.labels" . | nindent 4 }}
    {{- include "ai-stack.ollama.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.ollama.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ai-stack.ollama.selectorLabels" . | nindent 4 }}
